//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIV_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int orderId { get; set; }
        public string username { get; set; }
        public Nullable<int> dishId { get; set; }
        public int count { get; set; }
        public System.DateTime dateAndTime { get; set; }
        public string status { get; set; }
    
        public virtual tblDish tblDish { get; set; }

        //not mapping props
        public string dishName
        {
            get
            {
                return Service.GetPizzaName(dishId);
            }
        }

        public int? totalPrice
        {
            get
            {
                return Service.GetTotalPrice(orderId);
            }
        }
    }
}
