//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIV_Andreja_Kolesar.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrder
    {
        public int orderId { get; set; }
        public string username { get; set; }
        public Nullable<int> dishId { get; set; }
        public int count { get; set; }
        public System.DateTime dateAndTIme { get; set; }
        public Nullable<int> totalPrice { get; set; }
    }
}
